[workspace]
members = [
    "node",
    "pallets/dao",
    "pallets/dao-collective",
    "pallets/dao-membership",
    "pallets/dao-primitives",
    "pallets/dao-treasury",
    "runtime",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
